<a href="https://colab.research.google.com/github/RakeshRegala/ML-Workshop/blob/main/MLworkshop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.Perform arithmetic operations on NumPy arrays

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
addition = a + b
subtraction = a - b
multiplication = a * b
division = a / b

print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


#2. Write a script to compute the mean and standard deviation of a NumPy array.

In [ ]:
mean = np.mean(a)
std_dev = np.std(a)

print("Mean:", mean)
print("Standard Deviation:", std_dev)

Mean: 2.0
Standard Deviation: 0.816496580927726


#3. Create a NumPy array of integers from 10 to 50 with a step size of 5.


In [ ]:
arr = np.arange(10, 51, 5)
print("Array:", arr)

Array: [10 15 20 25 30 35 40 45 50]


#4. Reshape the array into a 2x4 matrix.


In [ ]:
arr=np.array([10, 15, 20, 25, 30, 35, 40, 45])
rearr=np.reshape(arr,(2,4))
print(rearr)

[[10 15 20 25]
 [30 35 40 45]]


#5. Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
• Extract the sub-matrix containing the last two rows and first two columns.
• Replace all elements greater than 4 with 0

In [ ]:
#  creating 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

subArr = arr[1:,:2]
print(subArr)

# replacing all elements greater than 4 with 0
arr[arr>4] = 0
print(arr)

[[4 5]
 [7 8]]
[[1 2 3]
 [4 0 0]
 [0 0 0]]


#6. Create two 1D arrays:
• a = np.array([1, 2, 3])
• b = np.array([4, 5, 6])
• Perform element-wise addition, multiplication, and division.


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a*b)
print(a/b)

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]


#7. Create a random NumPy array of size (4, 4). Compute:
• Mean of each column.
• Maximum value of the entire array.
• Sum of all elements.

In [ ]:
ranArr = np.random.rand(4,4)
print(ranArr)

print(np.mean(ranArr, axis = 0))
print(np.max(ranArr))
print(np.sum(ranArr))

[[0.12333126 0.07178994 0.19987489 0.55864371]
 [0.51109433 0.43105424 0.61866895 0.28975512]
 [0.91950067 0.14514653 0.56398759 0.26735622]
 [0.41681945 0.21645122 0.63314819 0.36237804]]
[0.49268643 0.21611048 0.50391991 0.36953327]
0.919500674957013
6.329000367687668


#8. Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply the result by 2

In [ ]:
arr = np.array([1, 2, 3, 4])
result = (arr + 10) * 2
print(result)

[22 24 26 28]


#9. Perform advanced slicing and indexing on a 3D array.
Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from
1 to 100. Perform the following:
• Extract the second "layer" (i.e., the second 2D array) in the first dimension.
• Extract the first two rows and the last three columns from each "layer."
• Replace all elements divisible by 3 with -1

In [ ]:
arr_3d = np.random.randint(1, 101, size=(3, 4, 5))

second_layer = arr_3d[1]

rows_cols = arr_3d[:, :2, -3:]

arr_3d[arr_3d % 3 == 0] = -1

print("Second Layer:\n", second_layer)
print("First Two Rows and Last Three Columns:\n", rows_cols)
print("Modified Array:\n", arr_3d)

Second Layer:
 [[89 10 -1 -1 13]
 [67 -1 91 95 22]
 [13 -1 55 14 41]
 [67 -1 26 46 31]]
First Two Rows and Last Three Columns:
 [[[65 65 -1]
  [-1 73 46]]

 [[-1 -1 13]
  [91 95 22]]

 [[-1 68 -1]
  [94 -1 -1]]]
Modified Array:
 [[[22 61 65 65 -1]
  [46 22 -1 73 46]
  [77 70 62 79 41]
  [74 -1 -1 59 -1]]

 [[89 10 -1 -1 13]
  [67 -1 91 95 22]
  [13 -1 55 14 41]
  [67 -1 26 46 31]]

 [[ 4 79 -1 68 -1]
  [41 50 94 -1 -1]
  [-1 -1 38 11 62]
  [-1 49 16 67 85]]]


#10. Work with broadcasting and advanced operations in NumPy.
 Create a NumPy array arr of shape (3, 3) with random integers between
 1 and 20. Perform the following:
• Subtract the mean of each row from its respective elements (row-wise
normalization).
• Create a new array by squaring all the elements in arr.
• Find the indices of the top 3 maximum values in the entire array

In [ ]:
arr = np.random.randint(1, 21, size=(3, 3))

row_means = np.mean(arr, axis=1).reshape(-1, 1)
normalized = arr - row_means
squared = arr ** 2

flat_indices = np.argsort(arr.ravel())[-3:]
indices = np.unravel_index(flat_indices, arr.shape)

print("Row-wise Normalized Array:\n", normalized)
print("Squared Array:\n", squared)
print("Indices of Top 3 Maximum Values:", list(zip(indices[0], indices[1])))

Row-wise Normalized Array:
 [[ 4.66666667 -8.33333333  3.66666667]
 [ 2.         -9.          7.        ]
 [11.         -7.         -4.        ]]
Squared Array:
 [[256   9 225]
 [144   1 289]
 [400   4  25]]
Indices of Top 3 Maximum Values: [(0, 0), (1, 2), (2, 0)]
